config/routes.rb
PlayfulList::Application.routes.draw do

  resources :lists do
    collection { post :sort }
    post 'add_level/:level_id', :action => :add_level
  end

  resources :sessions, :only => [:index] do
    collection do
      post 'start/:list_id', :action => :start, :as => 'start'
    end
    member do
      get  'play/:step/:iteration', :action => :play,      :as => "play"
      post 'play/:step/:iteration', :action => :completed, :as => 'completed'
      post 'too_many_attempts/:step/:iteration', :action => :too_many_attempts, :as => 'too_many_attempts'
      get  'hooray', :action => :finished_level,   :as => 'finished_level'
      get  'finish', :action => :finished_list,    :as => 'finished_list'
    end
    resources :sessions_iters, :as => :iters, :only => [:index]
  end

  devise_for :users

  get '/sign_in_as_demo_user' =>  'home#sign_in_as_demo_user'
  get '/por_que' => 'home#por_que'

  root :to => 'lists#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name
  attr_accessible :video

  belongs_to :user

  has_many :list_levels, :order => "position ASC"

  has_many :levels, :through => :list_levels

  validates :name, :presence => true

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # GET /lists
  # GET /lists.json
  before_filter :authenticate_user!

  def index
    p 'user authorized'
    @lists = current_user.lists

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = current_user.lists.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new
    @list.user = current_user
    @games = Game.all
    @levels = @list.levels.order("position")

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  def add_level
    list = current_user.lists.find(params[:list_id])
    list.list_levels.create level_id: params[:level_id]
    render nothing: true
  end

  def sort
    params[:id].each_with_index do |id, index|
      ListLevel.update_all({position: index+1}, {level_id: id})
    end
    render nothing: true
  end

  # GET /lists/1/edit
  def edit
    @list = current_user.lists.find(params[:id])
    @games = Game.all
    @levels = @list.levels
  end

  # POST /lists
  # POST /lists.json
  def create
    video = params[:video]
    params[:list][:video] = video[video.rindex("/")+1..video.rindex(".")-1]

    @list = List.new(params[:list])
    @list.user = current_user

    respond_to do |format|
      if @list.save
        format.html { redirect_to edit_list_url(@list.id), notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    video = params[:video]
    params[:list][:video] = video[video.rindex("/")+1..video.rindex(".")-1]

    @list = current_user.lists.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to lists_url, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = current_user.lists.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.haml
= content_for :head do
  :javascript
    $(document).ready(on_load_list_form)

= form_for @list do |f|
  - if @list.errors.any?
    #error_explanation.alert.alert-block.alert-error
      %h4= "#{pluralize(@list.errors.count, "error")} prohibited this list from being saved:"
      %ul
        - @list.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nombre, :id => :name
    = f.text_field :name

  %hr

  %h3
    Recompensa
    %br
    %br

    = hidden_field_tag(:video, "/assets/#{@list.video}.jpg")

    .row-fluid
      .span4
        .span12
          - if @list.video == 'backyardigans'
            = image_tag '/assets/backyardigans.jpg', :style => 'height:300px;cursor:pointer;', :class => 'reinforcement glow_effect'
          - else
            = image_tag '/assets/backyardigans.jpg', :style => 'height:300px;cursor:pointer;', :class => 'reinforcement'
      .span4
        .span12
          - if @list.video == 'lazytown'
            = image_tag '/assets/lazytown.jpg', :style => 'height:300px;cursor:pointer;', :class => 'reinforcement glow_effect'
          - else
            = image_tag '/assets/lazytown.jpg', :style => 'height:300px;cursor:pointer;', :class => 'reinforcement'
      .span4
        .span12
          - if @list.video == 'ben10'
            = image_tag '/assets/ben10.jpg', :style => 'height:300px;cursor:pointer;', :class => 'reinforcement glow_effect'
          - else
            = image_tag '/assets/ben10.jpg', :style => 'height:300px;cursor:pointer;', :class => 'reinforcement'


  %hr

  - if @list.id
    %h3
      Juegos

    %ol#levels{"data-update-url" => sort_lists_url}
      - @levels.each do |level|
        = content_tag_for :li, level do
          .well.well-small
            = level.name

    %br
    %span
      Agrega juegos a tu lista haciendo click en el que quieras:

    %br
    %br

    - games.each do |game|
      %h4
        = game.name
      %div{style: 'margin-right:800px;height:160px;width:100%;'}
        - game.levels.sort_by{|e| e[:order]}.each do |level|
          = render 'level_card', :game => game, :level => level, :list => @list

    .actions
      = f.submit 'Grabar', :class => 'btn btn-primary'
      = link_to 'Volver a mis listas', lists_path, :class => 'btn btn-link'
  -else
    .actions
      = f.submit 'Guardar y agregar juegos', :class => 'btn btn-primary'
      = link_to 'Volver a mis listas', lists_path, :class => 'btn btn-link'

app/views/lists/_level_card.haml
%button.add_level.well{style: 'width: 140px; height: 128px;padding:8px; float:left; margin-right: 10px;', 'data-level-id' => "#{level.id}", 'data-list-id' => "#{list.id}"}
  %div
    = "#{game.name} | Nivel #{level.order} "
  %h4
    = level.name
  = "Duración estimada: #{level.duration / 60} minutos"
  .clear

app/views/lists/edit.html.haml
%br

%h1 Modifica tu lista

= render 'form', :games => @games, :list => @list

app/views/lists/index.html.haml
%h2 Mis listas de juegos

%hr

- if @lists.empty?
  %br
  %p
    Aún no posees listas de juegos.
    = link_to 'Crea una nueva', new_list_path
  %br
  %br
- else
  %table
    - @lists.each do |list|
      %tr
        %td(style="padding: 10px")= list.name
        %td
          .btn-group
            = link_to 'Jugar', start_sessions_path(list.id), method: :post, :class => 'btn btn-success'
            = link_to 'Editar', edit_list_path(list), :class => 'btn btn-info'
            = link_to 'Ver estadísticas', sessions_path(list_id: list.id), :class => 'btn btn-info'
            = link_to 'Borrar', list, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-inverse'


  %hr

= link_to 'Nueva lista de juegos', new_list_path, :class => 'btn btn-primary'

%br
%br

app/views/lists/new.html.haml
%h1 Crea una lista

= render 'form', :games => Game.all, :list => @list

app/views/lists/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @list.name

= link_to 'Edit', edit_list_path(@list)
\|
= link_to 'Back', lists_path