config/routes.rb
PlayfulList::Application.routes.draw do

  resources :lists do
    collection { post :sort }
    post 'add_level/:level_id', :action => :add_level
  end

  resources :sessions, :only => [:index] do
    collection do
      post 'start/:list_id', :action => :start, :as => 'start'
    end
    member do
      get  'play/:step/:iteration', :action => :play,      :as => "play"
      post 'play/:step/:iteration', :action => :completed, :as => 'completed'
      post 'too_many_attempts/:step/:iteration', :action => :too_many_attempts, :as => 'too_many_attempts'
      get  'hooray', :action => :finished_level,   :as => 'finished_level'
      get  'finish', :action => :finished_list,    :as => 'finished_list'
    end
    resources :sessions_iters, :as => :iters, :only => [:index]
  end

  devise_for :users

  get '/sign_in_as_demo_user' =>  'home#sign_in_as_demo_user'
  get '/por_que' => 'home#por_que'

  root :to => 'lists#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/application.haml
!!! 5
%html
  %head
    %title
      ¡Puedo Jugar Solo!
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = render 'shared/google_analytics'
    = csrf_meta_tags
    = yield :head

%body
  .navbar
    .navbar-inner
      .brand
        %center
          %h1(style="font-family: 'Pacifico'; font-size: 56px;")
            %a{href:"/", style:"text-decoration:none;"}
              %span(style="color: #fdb02e") ¡Puedo
              %span(style="color: #F38630;") jugar
              %span(style="color: #FA6900;") solo!
    %ul.nav{style:"width:100%;background-color:#F38630;"}
      - if user_signed_in?
        %li{:class =>"#{"active" if params[:controller] == "lists"}"}
          =link_to "Mis Listas", lists_path
      %li{:class =>"#{"active" if params[:controller] == "home" && params[:action] = "por_que"}"}
        =link_to "¿Por qué 'Puedo Jugar Solo'?", por_que_path
      %ul.nav.pull-right
        - if user_signed_in?
          %li
            = link_to "Salir", destroy_user_session_path, :method => :delete
        - else
          %li
            = link_to "Crea una cuenta", new_user_registration_path
          %li
            = link_to "Entra", new_user_session_path
          %li
            = link_to "Ingresa con un usuario de prueba", sign_in_as_demo_user_path
  %div{ :class => "container " + (@body_css || "") }
    - unless notice.blank?
      .alert.alert-success
        = notice
    = yield

app/views/layouts/headless.haml
!!! 5
%html
  %head
    %title
      ¡Puedo Jugar Solo!
    = stylesheet_link_tag    "application", :media => "all"
    %style
      html, body { height: 100%; }
    = javascript_include_tag "application"
    = render 'shared/google_analytics'
    = csrf_meta_tags
    = yield :head

%body
  = yield